name: RetosKilam
version: '1.8-RELEASE'
main: rk.Ikrlegido12.retosKilam.RetosKilam
api-version: '1.19'
commands:
  RetosKilam:
    description: Plugin hecho para hacer retos.
    alisases:
      - rk
      - retos
      - kilam
